from django import forms
from .models import Suivipatient

class SuivipatientAdminForm(forms.ModelForm):
    CHOIX_MOL = [
        ('PHENOBARBITAL 30MG COMP', 'PHENOBARBITAL-GARDENAL-ALEPSAL 30MG COMP'),
        ('PHENOBARBITAL 60MG COMP', 'PHENOBARBITAL-GARDENAL-ALEPSAL 60MG COMP'),
        ('PHENYTOINE 100MG COMP', 'PHENYTOINE-DILANTIN 100MG COMP'),
        ('CARBAMAZEPINE 200MG COMP', 'CARBAMAZEPINE-TEGRETOL-NEUROTOP-CARBAMAL 200MG COMP'),
        ('VALPROATE DE SODIUM 200MG COMP', 'VALPROATE DE SODIUM-DEPAKINE-DEAMIDE 200MG COMP'),
        ('VALPROATE DE SODIUM 500MG COMP', 'VALPROATE DE SODIUM-DEPAKINE-DEAMIDE 500MG COMP'),
        ('VALPROATE DE SODIUM 300ML SIROP', 'VALPROATE DE SODIUM-DEPAKINE-DEAMIDE 300ML SIROP'),
        ('VALPROATE DE SODIUM 40ML SIROP', 'VALPROATE DE SODIUM-DEPAKINE-DEAMIDE 40ML SIROP'),
        ('LEVETIRACETAM 500MG COMP', 'LEVETIRACETAM 500MG COMP'),
        ('OLANZAPINE 10MG COMP', 'OLANZAPINE-ONALAP 10MG COMP'),
        ('RISPERIDONE 2MG COMP', 'RISPERIDONE-RISPERDAL-NORMADON 2MG COMP'),
        ('HALOPERIDOL 5MG COMP', 'HALOPERIDOL-HALDOL 5MG COMP'),
        ('HALOPERIDOL 100ML SIROP', 'HALOPERIDOL-HALDOL 100ML SIROP'),
        ('HALOPERIDOL 5MG AMP', 'HALOPERIDOL-HALDOL 5MG AMP'),
        ('CHLORPROMAZINE 100MG COMP', 'CHLORPROMAZINE-LARGACTIL 100MG COMP'),
        ('CHLORPROMAZINE 25MG COMP', 'CHLORPROMAZINE-LARGACTIL 25MG COMP'),
        ('CHLORPROMAZINE 25MG AMP', 'CHLORPROMAZINE-LARGACTIL 25MG AMP'),
        ('HALOPERIDOL DECANOATE 50MG AMP', 'HALOPERIDOL DECANOATE-HALDOL DECANOAS 50MG AMP'),
        ('AMYTRIPTYLINE 25MG COMP', 'AMYTRIPTYLINE-LAROXYL 25MG COMP'),
        ('FLUOXETINE 20MG GELULE', 'FLUOXETINE 20MG GELULE'),
        ('PAROXETINE 20MG COMP', 'PAROXETINE 20MG COMP'),
        ('SERTALINE 50MG COMP', 'SERTALINE 50MG COMP'),
        ('TRIHEXYPHENIDYL (ARTANE) 2MG COMP', 'TRIHEXYPHENIDYL (ARTANE) 2MG COMP'),
        ('PROMETHAZINE 25MG COMP', 'PROMETHAZINE-THERALENE 25MG COMP'),
        ('PROMETHAZINE 25MG AMP', 'PROMETHAZINE-THERALENE 25MG AMP'),
        ('DIAZEPAM 5MG COMP', 'DIAZEPAM 5MG COMP'),
        ('DIAZEPAM 5MG COMP', 'DIAZEPAM 5MG COMP'),
        ('DIAZEPAM 5MG AMP', 'DIAZEPAM 5MG AMP')  
    ]
    
    molecule = forms.MultipleChoiceField(
        choices=CHOIX_MOL,
        widget=forms.SelectMultiple,
        required = False,
    )

    class Meta:
        model = Suivipatient
        fields = '__all__'

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        return ",".join(tags)  # Convertir la liste en chaîne de caractères

