# Generated by Django 5.1 on 2024-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('pathologie', models.CharField(max_length=15)),
                ('centre_sante', models.CharField(max_length=50)),
                ('date_admission', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suivipatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_visite', models.DateField()),
                ('dotation', models.IntegerField()),
                ('nb_molecule', models.IntegerField()),
                ('type_molecule', models.CharField(max_length=25)),
                ('molecule', models.CharField(max_length=50)),
                ('etat_patient', models.CharField(max_length=20)),
                ('date_etat', models.DateField()),
                ('commentaire', models.TextField(max_length=100)),
                ('code_patient', models.ManyToManyField(blank=True, to='santementale.patient')),
            ],
        ),
    ]
