# Generated by Django 5.1 on 2024-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
