# Generated by Django 5.1 on 2024-08-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0003_alter_suivipatient_molecule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivipatient',
            name='commentaire',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suivipatient',
            name='date_etat',
            field=models.DateField(null=True),
        ),
    ]
