# Generated by Django 5.1 on 2024-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0004_alter_suivipatient_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivipatient',
            name='dotation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suivipatient',
            name='etat_patient',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suivipatient',
            name='nb_molecule',
            field=models.IntegerField(null=True),
        ),
    ]
