# Generated by Django 5.1 on 2024-08-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0005_alter_suivipatient_dotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivipatient',
            name='code_patient',
        ),
        migrations.AddField(
            model_name='suivipatient',
            name='code_patient',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
