# Generated by Django 5.1 on 2024-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0006_remove_suivipatient_code_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pathologie',
            field=models.CharField(blank=True, choices=[('DEP', 'Depression'), ('EPI', 'Epilepsie'), ('PSY', 'Psychose')], max_length=15),
        ),
    ]
