# Generated by Django 5.1 on 2024-08-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0007_alter_patient_pathologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='centre_sante',
            field=models.CharField(blank=True, choices=[('LANGUIBONOU', 'CSU LANGUIBONOU'), ('BOTRO', 'HG BOTRO'), ('KROFOINSOU', 'CSR KROFOINSOU'), ('FARI', 'CSR FARI MBABO'), ('BODOKRO', 'CSU BODOKRO'), ('MARABA', 'CSU MARABADJASSA'), ('ANDO', 'CSU ANDO-KEKRENOU'), ('POKOUKRO', 'CSU NGUESSAN POKOUKRO'), ('ASSANDRE', 'CSR ASSANDRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathologie',
            field=models.CharField(blank=True, choices=[('DEPRESSION', 'DEPRESSION'), ('EPILEPSIE', 'EPILEPSIE'), ('PSYCHOSE', 'PSYCHOSE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'FEMME'), ('H', 'HOMME'), ('FE', 'FE'), ('FA', 'FA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='suivipatient',
            name='etat_patient',
            field=models.CharField(choices=[('DCD', 'DECEDE'), ('TRANS-OUT', 'TRANSFERE-OUT'), ('TRANS-IN', 'TRANSFERE-IN'), ('AUTRES', 'AUTRES')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suivipatient',
            name='molecule',
            field=models.CharField(choices=[('PHENOBARBITAL', 'PHENOBARBITAL'), ('PHENYTOINE', 'PHENYTOINE'), ('CARBAMAZEPINE', 'CARBAMAZEPINE'), ('VALPROATE SE SODIUM', 'VALPROATE SE SODIUM'), ('LEVETIRACETAM', 'LEVETIRACETAM'), ('OLANZAPINE', 'OLANZAPINE'), ('RISPERIDONE', 'RISPERIDONE'), ('HALOPERIDOL', 'HALOPERIDOL'), ('CHLORPROMAZINE', 'CHLORPROMAZINE'), ('HALOPERIDOL DECANOATE', 'HALOPERIDOL DECANOATE'), ('AMYTRIPTYLINE', 'AMYTRIPTYLINE'), ('FLUOXETINE', 'FLUOXETINE'), ('PAROXETINE', 'PAROXETINE'), ('SERTALINE', 'SERTALINE'), ('TRIHEXYPHENIDYL (ARTANE)', 'ARTANE'), ('PROMETHAZINE', 'PROMETHAZINE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suivipatient',
            name='type_molecule',
            field=models.CharField(choices=[('ANTI-DEPRESSIF', 'ANTI-DEPRESSIF'), ('ANTI-PSYCHOTIQUE', 'ANTI-PSYCHOTIQUE'), ('ANTI-EPILEPTIQUE', 'ANTI-EPILEPTIQUE'), ('AUTRES', 'AUTRES')], max_length=25, null=True),
        ),
    ]
