# Generated by Django 5.1 on 2024-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0008_alter_patient_centre_sante_alter_patient_pathologie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivipatient',
            name='etat_patient',
            field=models.CharField(choices=[('DCD', 'DECEDE'), ('TRANS-OUT', 'TRANSFERE-OUT'), ('TRANS-IN', 'TRANSFERE-IN'), ('REFUS', 'REFUS VOLONTAIRE'), ('AUTRES', 'AUTRES')], max_length=20, null=True),
        ),
    ]
