# Generated by Django 5.1 on 2024-08-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santementale', '0009_alter_suivipatient_etat_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivipatient',
            name='code_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santementale.patient'),
        ),
    ]
